/**
 * Used to set the id of the database items, so it's not a 24-char-long hex ObjectID but is readable
 **/
export function getUserStringFromID(string: string): string {
	/*
		input string can be something like 61d1fbf70d5e97eb822cfad0
		every 2 chars is 1 byte, the bytes are according to this https://docs.mongodb.com/manual/reference/method/ObjectId/
	*/
	const datePart = string.slice(2, 5)		// get the 2nd and 3rd bytes of the timestamp, 1st doesnt change often and 3rd changes too often
	const counterPart = string.slice(18)	// get the 3 bytes of the incrmenting counter
	return (datePart + counterPart).toLowerCase()
}

// validate IDs that are visible to users, generated by the function above
export function validateUserString(string: unknown): string is string {
	if (!string) return false
	if (typeof string !== "string") return false // it's not a string so it's obviously wrong
	if (string.length !== 7) return false
	return true
}
